<a href="https://colab.research.google.com/github/BartoszJanJerzy/data-science-bootcamp/blob/master/01_sklearn_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sklearn
sklearn.__version__

'0.22.2.post1'

##Klasyfikacja (na danych oznaczonych)

In [24]:
import numpy as np
from sklearn import datasets

# ustawienie ziarna losowego
np.random.seed(10)
raw_data = datasets.load_iris()
raw_data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [ ]:
#info o danych
print(raw_data.DESCR)

In [12]:
# wstępne wyciecei danych do tablicy array
data = raw_data.data # zbiór ze zmiennymi niezależnymi (predyktory)
target = raw_data.target # zmienna zależna

In [13]:
# badanie kształtu tablic
print(data.shape)
print(target.shape)

(150, 4)
(150,)


In [14]:
# zazwyczaj dzieli się zbiór danych na dwie części: treningową (70-80%) i testową (20-30%)
# można to zrobić o tak:

from sklearn.model_selection import train_test_split

data_train,data_test, target_train, target_test = train_test_split(data, target, test_size=0.3)

In [15]:
print(data_train.shape)
print(target_train.shape)
print(data_test.shape)
print(target_test.shape)

(105, 4)
(105,)
(45, 4)
(45,)


In [16]:
# trening modelu

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(data_train, target_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
# teraz, co przewiduje tak wytrenowany model?
target_pred = model.predict(data_test)
target_pred

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 1, 0,
       1])

In [23]:
# OCENA MODELU

from sklearn.metrics import confusion_matrix, classification_report

# macierz konfuzji
# im większe wartości na przekatnej, tym lepiej dopasowany model
print(confusion_matrix(target_test, target_pred))

print('-'*200)

# informacje o otrzymanym modelu
print(classification_report(target_test,target_pred))

[[14  0  0]
 [ 0 17  0]
 [ 0  0 14]]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        14

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

