<a href="https://colab.research.google.com/github/BartoszJanJerzy/data-science-bootcamp/blob/master/06_array_indeksowanie_i_wycinanie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# wycinanie tak samo jak listy

# element z indeksem 2
print(a[2])

# element od indeksu 3 do końca
print(a[3:])

# indeksowanie od końca: ostatni element
print(a[-1])


2
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
19


In [ ]:
# wycinanie w tablicy 2D
a = a.reshape(4,5)
print(a)
print()

# cały pierwszy wiersz
print('First row', a[0])

# cała druga kolumna
print('Second column', a[:,1])

# konkretny element
print('Second row, second column', a[1,1])

# fragment tablicy
print('Rows 2,3 and columns 2-4\n', a[1:3, 1:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

First row [0 1 2 3 4]
Second column [ 1  6 11 16]
Second row, second column 6
Rows 2,3 and columns 2-4
 [[ 6  7  8]
 [11 12 13]]
