<a href="https://colab.research.google.com/github/BartoszJanJerzy/data-science-bootcamp/blob/master/1_Array_Tablice_NumPy_nDarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np # numerical Python

In [3]:
np.__version__

'1.18.5'

In [ ]:
# dostępne atrybuty od numpy

dir(np)

In [25]:
# podstaoowy obiekt numpy to tablice 'nD' (n = 1 / 2/ 3)
# komenda do tworzenia tablic to array

# tablica 1D
x = np.array([1,3])
print('1D array: ',x)

# ile wymiarów ma tablica?
print('\tNumber of dimensions: ',x.ndim)

# jaki kształt ma tablica?
print('\tShape of array:', x.shape)

# jaką wielkosć ma tablica?
print('\tSize of array is: ', x.size)

# jaki typ danych jest w tablicy?
print('\tType of values in array is: ', x.dtype)

1D array:  [1 3]
	Number of dimensions:  1
	Shape of array: (2,)
	Size of array is:  2
	Type of values in array is:  int64


In [24]:
# tablica 2D
x = np.array([[1,3,5.5], [-3, 2.5,6.7]])
print('2D array:\n',x)

# ile wymiarów ma tablica?
print('\tNumber of dimensions: ',x.ndim)

# jaki kształt ma tablica?
print('\tShape of array:', x.shape)

# jaką wielkosć ma tablica?
print('\tSize of array is: ', x.size)

# jaki typ danych jest w tablicy?
print('\tType of values in array is: ', x.dtype)

2D array:
 [[ 1.   3.   5.5]
 [-3.   2.5  6.7]]
	Number of dimensions:  2
	Shape of array: (2, 3)
	Size of array is:  6
	Type of values in array is:  float64


In [26]:
# tablica 3D: dla lepszej wizualizacji kodu można pisać w kilku linijkach
x = np.array(
    [[[4,3,1],
      [3,1,2]],
     [[4,1,3],
      [4,2,1]]]
)
print('3D array:\n',x)

# ile wymiarów ma tablica?
print('\tNumber of dimensions: ',x.ndim)

# jaki kształt ma tablica?
print('\tShape of array:', x.shape)

# jaką wielkosć ma tablica?
print('\tSize of array is: ', x.size)

# jaki typ danych jest w tablicy?
print('\tType of values in array is: ', x.dtype)

3D array:
 [[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]]
	Number of dimensions:  3
	Shape of array: (2, 2, 3)
	Size of array is:  12
	Type of values in array is:  int64
