<a href="https://colab.research.google.com/github/BartoszJanJerzy/data-science-bootcamp/blob/master/2_Array_tworzenie_tablic_NumPy_ndArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
# tablica złozona z samych 0
# domyślnie wartości są float
print('2D 0-array with float:\n', np.zeros(shape=(4,10)))

# a jesli chcę z int
print('\n2D 0-array with int:\n', np.zeros(shape=(4,10), dtype='int'))

2D 0-array with float:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

2D 0-array with int:
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [10]:
# podobnie z 1-kami
print('2D 1-array with float:\n', np.ones(shape=(4,10)))

# a jesli chcę z int
print('\n2D 1-array with int:\n', np.ones(shape=(4,10), dtype='int'))

2D 1-array with float:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

2D 1-array with int:
 [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [12]:
# a jeśli chcę kontrolwoać wartości?

print('2D array with float:\n', np.full(shape=(4,10), fill_value=4))

# a jesli chcę z int
print('\n2D 0-array with int:\n', np.full(shape=(4,10), fill_value=4, dtype='int'))

2D array with float:
 [[4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]]

2D 0-array with int:
 [[4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]]


In [17]:
# generowanie tablicy 1D funkcją arange()
# ostatni element się nie wlicza!
print(np.arange(10))

# a w konkretnym zakresie
print(np.arange(start=5, stop=10))

# można też ustalić krok
print(np.arange(start=10, stop=100, step=10))

# krok może być ujemny -> tablica malejąca
print(np.arange(start=100, stop=10, step= -10))

# krok może być typu float
print(np.arange(start=100, stop=10, step= -10.5))

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[10 20 30 40 50 60 70 80 90]
[100  90  80  70  60  50  40  30  20]
[100.   89.5  79.   68.5  58.   47.5  37.   26.5  16. ]


In [19]:
# generowanie liczb rozłozonyhc równo w danym zakresie
print(np.linspace(start=0, stop=1, num=11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [21]:
# zmiana kształtu tablicy
a = np.arange(15)
print('Array a is\n', a)
print()

# dobieramy samodzielnei rozmiar aby zgadzał się
b = a.reshape((3,5))
print('Array with given rows (3) and columns (5) is:\n', b)
print()

# definiujemy liczbę wierszy, a Python dobiera liczbę kolumn (-1)
c = a.reshape((3, -1))
print('Array with given rows (3) and automatic columns:\n', c)
print()

# definiujemy liczbę kolumn a Python dobiera wiersze (-1)
d = a.reshape((-1,3))
print('Array with given columns (3) and autoamitc rows:\n', d)

Array a is
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Array with given rows (3) and columns (5) is:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Array with given rows (3) and automatic columns:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Array with given columns (3) and autoamitc rows:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
