<a href="https://colab.research.google.com/github/BartoszJanJerzy/data-science-bootcamp/blob/master/3_Array_podstawowe_operacje_na_tablicach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# dwie tablice na których bedą pokazywane operacje
a = np.array([3,1,4,2])
b = np.array([3,-1,3,2])

In [7]:
# dodwanie tablic: lczba elementów musi być taka sama!
print('Array a={}, array b={}, their sum is a+b={}'.format(a,b,a+b))

# np.add(a,b)

Array a=[3 1 4 2], array b=[ 3 -1  3  2], their sum is a+b=[6 0 7 4]


In [8]:
# różnica tablic: lczba elementów musi być taka sama!
print('Array a={}, array b={}, their difference is a-b={}'.format(a,b,a-b))

# np.subtract(a,b)

Array a=[3 1 4 2], array b=[ 3 -1  3  2], their difference is a-b=[0 2 1 0]


In [13]:
# mnożenie tablic: lczba elementów musi być taka sama!
print('Array a={}, array b={}, their product is a*b={}'.format(a,b,a*b))

# np.multiply(a,b)

Array a=[3 1 4 2], array b=[ 3 -1  3  2], their product is a*b=[ 9 -1 12  4]


In [14]:
# dzielenie tablic: lczba elementów musi być taka sama!
# wynik to zawsze float
print('Array a={}, array b={}, their quotient is a/b={}'.format(a,b,a/b))

# np.divide(a,b)

Array a=[3 1 4 2], array b=[ 3 -1  3  2], their quotient is a/b=[ 1.         -1.          1.33333333  1.        ]


In [19]:
# przykałdowe oepracje na pojedynczych tablicach
print(a,'+ 3 =',a+3)
print('abs({}) = {}'.format(b,abs(b)))

[3 1 4 2] + 3 = [6 4 7 5]
abs([ 3 -1  3  2]) = [3 1 3 2]


In [22]:
# można też łączyćze sobą te operacje...
print(np.add(a,abs(b-5)))

[5 7 6 5]


In [35]:
x = np.array([[1,3],[-2,0]])
y = np.array([[6,0],[-1,2]])
            
# mnożenie macierzy
# zwykłe mnożenie * pomnozy przez siebie odpowiadajaće sobie komórki:
print('Array x:\n{}\n\nArray y\n{}\n\nTheir product "*"\n{}\n'.format(x,y,x*y))
print('-'*50,'\n')

# mnożenie macierzowe np.dot()
print('Array x:\n{}\n\nArray y\n{}\n\nTheir matrix multiplication:\n{}\n'.format(x,y,np.dot(x,y)))
print('-'*50,'\n')

# macierze można mnożyć na macierzy
# nie zmienia to oryginalnej maceirzy
print('x.dot(y)\n',x.dot(y)) # to samo x @ y
print()

# mnożenie macierzowe nie jest przemienne!
print('y.dot(x)\n',y.dot(x)) 

Array x:
[[ 1  3]
 [-2  0]]

Array y
[[ 6  0]
 [-1  2]]

Their product "*"
[[6 0]
 [2 0]]

-------------------------------------------------- 

Array x:
[[ 1  3]
 [-2  0]]

Array y
[[ 6  0]
 [-1  2]]

Their matrix multiplication:
[[  3   6]
 [-12   0]]

-------------------------------------------------- 

x.dot(y)
 [[  3   6]
 [-12   0]]

y.dot(x)
 [[ 6 18]
 [-5 -3]]
