<a href="https://colab.research.google.com/github/BartoszJanJerzy/data-science-bootcamp/blob/master/4_Array_generowanie_liczb_pseudolosowych.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
# losowe wartości z rozkładu normalnego
# M=0, SD=1

# jedna wartość
print(np.random.randn())
print()

# wybrana ilośc wartości, np. 10
print(np.random.randn(10))
print()

# wybrana ilośc wartości w macierzy: 4 kolumny, 10 wierszy
print(np.random.randn(10,4))

-1.2679664494799343

[ 0.06621689 -0.98150582 -2.75234311  0.20459052  2.82199031  1.2091346
  0.04466325  1.79174455 -1.43240288 -0.82760709]

[[-0.50339338  1.74737533  1.41380029 -0.67219736]
 [ 0.35801553  0.70491878 -1.50664989  1.02053471]
 [-0.44865939  0.48084358  0.07254297  2.33063349]
 [ 1.0544315   0.0227078   0.30116025  0.22178238]
 [-1.04064785  0.79449803  0.10221673 -0.09365756]
 [-1.03175928  1.51980182  0.22675213 -0.69856631]
 [-1.82255031 -0.11968033  1.35460614  1.43201934]
 [ 0.72760603 -1.32457978 -0.42087725 -0.07748592]
 [-1.10243077 -0.62886605  0.74745809  0.42283465]
 [ 0.38236998 -0.71054488 -0.26363044 -0.39614889]]


In [13]:
# liczby losowe w zakresie 0-1
print(np.random.rand())
print()

# macierz liczb losowych (10 wierszy,2 kolumny) w zakresei 0-1
print(np.random.rand(10,2))
print()

# liczba losowa całkowita w wybranym zakresie, np. 0-9
print(np.random.randint(10))
print()

# liczba losowa całkowita w wybranym zakresie, np. 10-99
print(np.random.randint(low=10, high=100))
print()

# liczba losowa całkowita w wybranym zakresie, np. 10-99
# w macierzy 2 wiersze x 10 kolumn
print(np.random.randint(low=10, high=100, size=(2,10)))
print()

0.39167816595593685

[[0.4907649  0.74753396]
 [0.27228142 0.42765893]
 [0.70056553 0.39679934]
 [0.20487381 0.14458078]
 [0.66878618 0.06804794]
 [0.90543519 0.49723578]
 [0.21023746 0.89870277]
 [0.79613292 0.01077235]
 [0.11235863 0.03690843]
 [0.78361218 0.69680761]]

8

69

[[75 85 56 33 18 78 67 26 99 89]
 [86 32 56 91 33 55 16 87 41 34]]



In [19]:
# wybór losowy z podanych danych
a = np.arange(10)
print(np.random.choice(a))

# to samo na danych tekstowych
scripts = ['pytho','java','sql']
print(np.random.choice(scripts))

2
pytho


In [28]:
# tasowanie danych
data = np.arange(20)
np.random.shuffle(data)
data

array([ 3, 13,  2,  7, 15, 17, 10, 12, 14,  9,  6, 11,  4,  5, 16,  1, 19,
        0, 18,  8])