<a href="https://colab.research.google.com/github/BartoszJanJerzy/data-science-bootcamp/blob/master/7_array_iteracja_po_tablicach%2C_zmiana_rozmiaru_tablic_oraz_maski_logiczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.arange(20)
a = a.reshape(4,5)

In [3]:
# iterowanie po wierszach
for row in a:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [4]:
# iterowanie po wybranych elementach z wierszy
for row in a:
  print(row[:2])

[0 1]
[5 6]
[10 11]
[15 16]


In [5]:
# iterowanie po kolejnych elementach
for item in a.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [9]:
# zmiana kształtu
b = a.reshape(5,4)
print(b)
print()

# wypłaszczenie
print(b.ravel())
print()

# transponowanie macierzy (wiersze na kolumny)
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [22]:
a = np.arange(start=-10,stop=10,step=0.5)
a = a.reshape(10,-1)
print(a)
print()

# maski logiczne
# czy element spełnia warunek logiczny? np > 0
print(a > 0)
print()

# wycięcie elementó spełniajacych warunek
print(a[a>0])
print()

# łączenie warunków
filter1 = np.bitwise_and(a>0, a<5)
filter2 = np.bitwise_or(a<-5, a>5)
print(a[filter1])
print(a[filter2])

[[-10.   -9.5  -9.   -8.5]
 [ -8.   -7.5  -7.   -6.5]
 [ -6.   -5.5  -5.   -4.5]
 [ -4.   -3.5  -3.   -2.5]
 [ -2.   -1.5  -1.   -0.5]
 [  0.    0.5   1.    1.5]
 [  2.    2.5   3.    3.5]
 [  4.    4.5   5.    5.5]
 [  6.    6.5   7.    7.5]
 [  8.    8.5   9.    9.5]]

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.
 9.5]

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5   5.5   6.
   6.5   7.    7.5   8.    8.5   9.    9.5]
