<a href="https://colab.research.google.com/github/BartoszJanJerzy/data-science-bootcamp/blob/master/8_algebra_liniowa_norma_wektora_i_odleg%C5%82o%C5%9B%C4%87_punkt%C3%B3w.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Wektory i punkty

In [6]:
# tworzenie wektora
v1 = np.array([0,4])
print(v1)

# norma (długość wektora) w przestrzeni R2
print(np.linalg.norm(v1))

# norma (długość) w przestrzeni Euklidesowej Rn
v2 = np.array([-10,10,13])
print(np.linalg.norm(v2))

[0 4]
4.0
19.209372712298546


In [9]:
# odległość między dwoma punktami w przestrzeni R2
p = np.array([0,3])
q = np.array([4,0])

np.linalg.norm(p-q)

# tak samo działą w przestrzeni Rn

5.0

# Mnożenie macierzy
### Warunek: liczba kolumn w macierzy 2' musi być równa ilości wierszy w macierzy 1'

In [20]:
# przykąłd mnożenia macierzy
X = np.array([[5,3],[3,9]])
Y = np.array([1,-1])
Z = np.dot(X,Y)

print("Macierz X:\n{}\n\nMacierz Y:\n{}\n".format(X,Y))
print("Efektem mnożenia jest macierz:",Z)
print('[5*1 + 3*(-1)    3*1 + 9*(-1)]')

Macierz X:
[[5 3]
 [3 9]]

Macierz Y:
[ 1 -1]

Efektem mnożenia jest macierz: [ 2 -6]
[5*1 + 3*(-1)    3*1 + 9*(-1)]


# Wyznacznik macierzy
### Różnica iloczynów elementów przekątnych

In [23]:
# obliczanie wyznaczniku macierzy
A = np.array([[2,4],[-1,3]])
round(np.linalg.det(A))

10.0

# Ślad macierzy
### Suma elementów po przekątnej

In [24]:
# obliczanie śladu macierzy
np.trace(A)

5

# Macierz jednostkowa
### suma elementów w kolumnach i wierszach to 1

In [25]:
# tworzenie macierzy jednostkowej
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Macierz odwrotna
### macierz kwadratowa stopnia *n*. Macierz A posiada maceirz odwrtoną, gdy istnieje maceirz B, taka że:
###AB = BA = I (jednostkowa)

In [28]:
# jak znaleźć macierz odwrotną?
B = np.linalg.inv(A)

np.set_printoptions(precision=4, suppress=True) #dokładnośc wyświetlanych liczb

print('Matrix A:\n',A)
print()
print('Matrix B (inversed A):\n',B)
print()
print('np.dot(A,B):\n',np.dot(A,B))

Matrix A:
 [[ 2  4]
 [-1  3]]

Matrix B (inversed A):
 [[ 0.3 -0.4]
 [ 0.1  0.2]]

np.dot(A,B):
 [[1. 0.]
 [0. 1.]]


# Macierz transponowana
### Zamianawierszy na kolumny

In [30]:
# transponowanie macierzy
print(A)
print()
print(np.transpose(A))

[[ 2  4]
 [-1  3]]

[[ 2 -1]
 [ 4  3]]


#Rozwiazywanie układu równań na macierzy

In [34]:
A = np.array([[2,4],[1,-1]]) # macierz współczynników
B = np.array([[10],[-1]]) #macierz wyrazów wolnych
A_inv = np.linalg.inv(A) # maceirz odwrotna do A
X = np.dot(A_inv,B) # macierz z wynikami

print('Równanie:\n\t2x + 4y = 10\n\tx - y = -1')
print()
print('Macierz A współczynników:\n',A)
print()
print('Macierz B wyrazów wolnych\n',B)
print()
print('Macierz odwrotna do A:\n',A_inv)
print()
print('Macierz z wynikami (np.dot(A_inv,B)):\n',X)
print()
print('Rozwiązanie: x={}, y={}'.format(X[0],X[1]))

Równanie:
	2x + 4y = 10
	x - y = -1

Macierz A współczynników:
 [[ 2  4]
 [ 1 -1]]

Macierz B wyrazów wolnych
 [[10]
 [-1]]

Macierz odwrotna do A:
 [[ 0.1667  0.6667]
 [ 0.1667 -0.3333]]

Macierz z wynikami (np.dot(A_inv,B)):
 [[1.]
 [2.]]

Rozwiązanie: x=[1.], y=[2.]
